export enum OrderStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ORDERED_FROM_SUPPLIER = 'ORDERED_FROM_SUPPLIER',
  READY_FOR_BILLING = 'READY_FOR_BILLING',
  AWAITING_PAYMENT_VERIFICATION = 'AWAITING_PAYMENT_VERIFICATION',
  PAID = 'PAID',
  DELIVERED = 'DELIVERED',
}
