/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation PayInvoiceByOrderId($orderId: Int!) {\n    payInvoiceByOrderId(orderId: $orderId) {\n      invoiceId\n      orderId\n      invoiceNumber\n      totalAmount\n      paymentStatus\n      dueDate\n      updatedAt\n    }\n  }\n": typeof types.PayInvoiceByOrderIdDocument,
    "\n  query GetAllInvoices {\n    allInvoices {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetAllInvoicesDocument,
    "\n  query GetInvoiceById($invoiceId: Int!) {\n    invoiceByOrderId(orderId: $invoiceId) {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetInvoiceByIdDocument,
    "\n  query GetCategories {\n    getCategories {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetCategoriesDocument,
    "\n  mutation CreateCategory($input: CreateCategoryDto!) {\n    createCategory(input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateCategoryDocument,
    "\n  mutation UpdateCategory($id: Int!, $input: UpdateCategoryDto!) {\n    updateCategory(id: $id, input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateCategoryDocument,
    "\n  mutation DeleteCategory($categoryId: Int!) {\n    deleteCategory(categoryId: $categoryId) {\n      categoryId\n    }\n  }\n": typeof types.DeleteCategoryDocument,
    "\n  mutation AssignRandomCategoriesToProducts {\n    assignRandomCategoriesToProducts {\n      message\n      count\n    }\n  }\n": typeof types.AssignRandomCategoriesToProductsDocument,
    "\n  mutation CreateProduct($input: CreateProductDto!) {\n    createProduct(input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n": typeof types.CreateProductDocument,
    "\n  mutation UpdateProduct($id: Int!, $input: UpdateProductDto!) {\n    updateProduct(id: $id, input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n": typeof types.UpdateProductDocument,
    "\n  mutation DeleteProduct($productId: Int!) {\n    deleteProduct(productId: $productId) {\n        productId\n    }\n}\n": typeof types.DeleteProductDocument,
    "\n  query GetProducts {\n    getProducts {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      blocked\n      inTransit\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetProductsDocument,
    "\n  query GetProductById($productId: Int!) {\n    getProductById(productId: $productId) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetProductByIdDocument,
    "\n  query GetProductByName($productName: String!) {\n    getProductByName(productName: $productName) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.GetProductByNameDocument,
    "\n  mutation RejectPaymentProof($input: RejectPaymentProofDto!) {\n    rejectPaymentProof(input: $input) {\n      orderId\n      status\n      paymentProofStatus\n      paymentProofAttempts\n      paymentProofRejectionReason\n      rejectionReason\n    }\n  }\n": typeof types.RejectPaymentProofDocument,
    "\n  mutation CreateAdminOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateAdminOrderDocument,
    "\n  mutation UpdateAdminOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateAdminOrderDocument,
    "\n  mutation TransitionAdminOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.TransitionAdminOrderStatusDocument,
    "\n  query AllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.AllOrdersDocument,
    "\n  query OrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.OrderDetailsDocument,
    "\n  query ClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.ClientOrdersDocument,
    "\n  mutation Login($emailAddress: String!, $password: String!) {\n    login(emailAddress: $emailAddress, password: $password) {\n        message\n    }\n  }\n": typeof types.LoginDocument,
    "\n  mutation Logout {\n    logout {\n      message\n    }\n  }\n": typeof types.LogoutDocument,
    "\n  query readProfile {\n    readProfile {\n      userId\n      fullName\n      emailAddress\n      companyName\n      address\n      phoneNumber\n      role\n    }\n  }\n": typeof types.ReadProfileDocument,
    "\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      userId\n      productId\n      quantity\n      unitPrice\n      selectedColor\n      selectedSize\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.AddToCartDocument,
    "\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      quantity\n      updatedAt\n    }\n  }\n": typeof types.UpdateCartItemDocument,
    "\n  mutation RemoveFromCart($itemId: Int!) {\n    removeFromCart(itemId: $itemId)\n  }\n": typeof types.RemoveFromCartDocument,
    "\n  mutation ClearCart {\n    clearCart\n  }\n": typeof types.ClearCartDocument,
    "\n  mutation RemoveCartItemByProductId($productId: Int!) {\n    removeCartItemByProductId(productId: $productId)\n  }\n": typeof types.RemoveCartItemByProductIdDocument,
    "\n  mutation PlaceOrder($input: PlaceOrderInput!) {\n    placeOrder(input: $input) {\n      success\n      orderNumber\n      message\n      orderId\n      createdAt\n    }\n  }\n": typeof types.PlaceOrderDocument,
    "\n  query GetCart {\n    getCart {\n      items {\n        id\n        userId\n        productId\n        quantity\n        unitPrice\n        selectedColor\n        selectedSize\n        createdAt\n        updatedAt\n        product {\n          productId\n          productName\n          imageUrl\n          productDescription\n          productPrice\n          category {\n            categoryId\n            categoryName\n          }\n        }\n      }\n      totalItems\n      totalPrice\n    }\n  }\n": typeof types.GetCartDocument,
    "\n  mutation InitiatePaymongoCheckout($orderId: Int!) {\n    initiatePaymongoCheckout(orderId: $orderId) {\n      success\n      paymentIntentId\n      checkoutUrl\n      message\n    }\n  }\n": typeof types.InitiatePaymongoCheckoutDocument,
    "\n  mutation CreateOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreateOrderDocument,
    "\n  mutation UpdateOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.UpdateOrderDocument,
    "\n  mutation TransitionOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.TransitionOrderStatusDocument,
    "\n  query GetClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n": typeof types.GetClientOrdersDocument,
    "\n  query GetOrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n": typeof types.GetOrderDetailsDocument,
    "\n  query GetAllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n": typeof types.GetAllOrdersDocument,
    "\n  query GetNotificationsByUserId {\n    getNotificationsByUserId {\n      notificationId\n      userId\n      type\n      title\n      message\n      orderId\n      isRead\n      createdAt\n      readAt\n      metadata\n    }\n  }\n": typeof types.GetNotificationsByUserIdDocument,
    "\n  mutation MarkNotificationAsRead($notificationId: Int!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n": typeof types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n": typeof types.MarkAllNotificationsAsReadDocument,
};
const documents: Documents = {
    "\n  mutation PayInvoiceByOrderId($orderId: Int!) {\n    payInvoiceByOrderId(orderId: $orderId) {\n      invoiceId\n      orderId\n      invoiceNumber\n      totalAmount\n      paymentStatus\n      dueDate\n      updatedAt\n    }\n  }\n": types.PayInvoiceByOrderIdDocument,
    "\n  query GetAllInvoices {\n    allInvoices {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetAllInvoicesDocument,
    "\n  query GetInvoiceById($invoiceId: Int!) {\n    invoiceByOrderId(orderId: $invoiceId) {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetInvoiceByIdDocument,
    "\n  query GetCategories {\n    getCategories {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetCategoriesDocument,
    "\n  mutation CreateCategory($input: CreateCategoryDto!) {\n    createCategory(input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateCategoryDocument,
    "\n  mutation UpdateCategory($id: Int!, $input: UpdateCategoryDto!) {\n    updateCategory(id: $id, input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateCategoryDocument,
    "\n  mutation DeleteCategory($categoryId: Int!) {\n    deleteCategory(categoryId: $categoryId) {\n      categoryId\n    }\n  }\n": types.DeleteCategoryDocument,
    "\n  mutation AssignRandomCategoriesToProducts {\n    assignRandomCategoriesToProducts {\n      message\n      count\n    }\n  }\n": types.AssignRandomCategoriesToProductsDocument,
    "\n  mutation CreateProduct($input: CreateProductDto!) {\n    createProduct(input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n": types.CreateProductDocument,
    "\n  mutation UpdateProduct($id: Int!, $input: UpdateProductDto!) {\n    updateProduct(id: $id, input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n": types.UpdateProductDocument,
    "\n  mutation DeleteProduct($productId: Int!) {\n    deleteProduct(productId: $productId) {\n        productId\n    }\n}\n": types.DeleteProductDocument,
    "\n  query GetProducts {\n    getProducts {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      blocked\n      inTransit\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetProductsDocument,
    "\n  query GetProductById($productId: Int!) {\n    getProductById(productId: $productId) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetProductByIdDocument,
    "\n  query GetProductByName($productName: String!) {\n    getProductByName(productName: $productName) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n": types.GetProductByNameDocument,
    "\n  mutation RejectPaymentProof($input: RejectPaymentProofDto!) {\n    rejectPaymentProof(input: $input) {\n      orderId\n      status\n      paymentProofStatus\n      paymentProofAttempts\n      paymentProofRejectionReason\n      rejectionReason\n    }\n  }\n": types.RejectPaymentProofDocument,
    "\n  mutation CreateAdminOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateAdminOrderDocument,
    "\n  mutation UpdateAdminOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateAdminOrderDocument,
    "\n  mutation TransitionAdminOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": types.TransitionAdminOrderStatusDocument,
    "\n  query AllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": types.AllOrdersDocument,
    "\n  query OrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": types.OrderDetailsDocument,
    "\n  query ClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n": types.ClientOrdersDocument,
    "\n  mutation Login($emailAddress: String!, $password: String!) {\n    login(emailAddress: $emailAddress, password: $password) {\n        message\n    }\n  }\n": types.LoginDocument,
    "\n  mutation Logout {\n    logout {\n      message\n    }\n  }\n": types.LogoutDocument,
    "\n  query readProfile {\n    readProfile {\n      userId\n      fullName\n      emailAddress\n      companyName\n      address\n      phoneNumber\n      role\n    }\n  }\n": types.ReadProfileDocument,
    "\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      userId\n      productId\n      quantity\n      unitPrice\n      selectedColor\n      selectedSize\n      createdAt\n      updatedAt\n    }\n  }\n": types.AddToCartDocument,
    "\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      quantity\n      updatedAt\n    }\n  }\n": types.UpdateCartItemDocument,
    "\n  mutation RemoveFromCart($itemId: Int!) {\n    removeFromCart(itemId: $itemId)\n  }\n": types.RemoveFromCartDocument,
    "\n  mutation ClearCart {\n    clearCart\n  }\n": types.ClearCartDocument,
    "\n  mutation RemoveCartItemByProductId($productId: Int!) {\n    removeCartItemByProductId(productId: $productId)\n  }\n": types.RemoveCartItemByProductIdDocument,
    "\n  mutation PlaceOrder($input: PlaceOrderInput!) {\n    placeOrder(input: $input) {\n      success\n      orderNumber\n      message\n      orderId\n      createdAt\n    }\n  }\n": types.PlaceOrderDocument,
    "\n  query GetCart {\n    getCart {\n      items {\n        id\n        userId\n        productId\n        quantity\n        unitPrice\n        selectedColor\n        selectedSize\n        createdAt\n        updatedAt\n        product {\n          productId\n          productName\n          imageUrl\n          productDescription\n          productPrice\n          category {\n            categoryId\n            categoryName\n          }\n        }\n      }\n      totalItems\n      totalPrice\n    }\n  }\n": types.GetCartDocument,
    "\n  mutation InitiatePaymongoCheckout($orderId: Int!) {\n    initiatePaymongoCheckout(orderId: $orderId) {\n      success\n      paymentIntentId\n      checkoutUrl\n      message\n    }\n  }\n": types.InitiatePaymongoCheckoutDocument,
    "\n  mutation CreateOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreateOrderDocument,
    "\n  mutation UpdateOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n": types.UpdateOrderDocument,
    "\n  mutation TransitionOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n": types.TransitionOrderStatusDocument,
    "\n  query GetClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n": types.GetClientOrdersDocument,
    "\n  query GetOrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n": types.GetOrderDetailsDocument,
    "\n  query GetAllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n": types.GetAllOrdersDocument,
    "\n  query GetNotificationsByUserId {\n    getNotificationsByUserId {\n      notificationId\n      userId\n      type\n      title\n      message\n      orderId\n      isRead\n      createdAt\n      readAt\n      metadata\n    }\n  }\n": types.GetNotificationsByUserIdDocument,
    "\n  mutation MarkNotificationAsRead($notificationId: Int!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n": types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n": types.MarkAllNotificationsAsReadDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation PayInvoiceByOrderId($orderId: Int!) {\n    payInvoiceByOrderId(orderId: $orderId) {\n      invoiceId\n      orderId\n      invoiceNumber\n      totalAmount\n      paymentStatus\n      dueDate\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation PayInvoiceByOrderId($orderId: Int!) {\n    payInvoiceByOrderId(orderId: $orderId) {\n      invoiceId\n      orderId\n      invoiceNumber\n      totalAmount\n      paymentStatus\n      dueDate\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllInvoices {\n    allInvoices {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetAllInvoices {\n    allInvoices {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetInvoiceById($invoiceId: Int!) {\n    invoiceByOrderId(orderId: $invoiceId) {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetInvoiceById($invoiceId: Int!) {\n    invoiceByOrderId(orderId: $invoiceId) {\n      invoiceId\n      orderId\n      userId\n      invoiceNumber\n      totalAmount\n      dueDate\n      paymentStatus\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCategories {\n    getCategories {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetCategories {\n    getCategories {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateCategory($input: CreateCategoryDto!) {\n    createCategory(input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateCategory($input: CreateCategoryDto!) {\n    createCategory(input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateCategory($id: Int!, $input: UpdateCategoryDto!) {\n    updateCategory(id: $id, input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateCategory($id: Int!, $input: UpdateCategoryDto!) {\n    updateCategory(id: $id, input: $input) {\n      categoryId\n      categoryName\n      slug\n      skuPrefix\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteCategory($categoryId: Int!) {\n    deleteCategory(categoryId: $categoryId) {\n      categoryId\n    }\n  }\n"): (typeof documents)["\n  mutation DeleteCategory($categoryId: Int!) {\n    deleteCategory(categoryId: $categoryId) {\n      categoryId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AssignRandomCategoriesToProducts {\n    assignRandomCategoriesToProducts {\n      message\n      count\n    }\n  }\n"): (typeof documents)["\n  mutation AssignRandomCategoriesToProducts {\n    assignRandomCategoriesToProducts {\n      message\n      count\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateProduct($input: CreateProductDto!) {\n    createProduct(input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n"): (typeof documents)["\n  mutation CreateProduct($input: CreateProductDto!) {\n    createProduct(input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateProduct($id: Int!, $input: UpdateProductDto!) {\n    updateProduct(id: $id, input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n"): (typeof documents)["\n  mutation UpdateProduct($id: Int!, $input: UpdateProductDto!) {\n    updateProduct(id: $id, input: $input) {\n        productId\n        productName\n        productDescription\n        imageUrl\n        sku\n        categoryId\n        category {\n          categoryId\n          categoryName\n          slug\n        }\n        productPrice\n        reorderPoint\n        available\n        blocked\n        inTransit\n        createdAt\n        updatedAt\n    }\n}\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteProduct($productId: Int!) {\n    deleteProduct(productId: $productId) {\n        productId\n    }\n}\n"): (typeof documents)["\n  mutation DeleteProduct($productId: Int!) {\n    deleteProduct(productId: $productId) {\n        productId\n    }\n}\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProducts {\n    getProducts {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      blocked\n      inTransit\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetProducts {\n    getProducts {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      blocked\n      inTransit\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductById($productId: Int!) {\n    getProductById(productId: $productId) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetProductById($productId: Int!) {\n    getProductById(productId: $productId) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetProductByName($productName: String!) {\n    getProductByName(productName: $productName) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query GetProductByName($productName: String!) {\n    getProductByName(productName: $productName) {\n      productId\n      productName\n      productDescription\n      sku\n      categoryId\n      imageUrl\n      category {\n        categoryId\n        categoryName\n        slug\n      }\n      productPrice\n      reorderPoint\n      available\n      inTransit\n      blocked\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RejectPaymentProof($input: RejectPaymentProofDto!) {\n    rejectPaymentProof(input: $input) {\n      orderId\n      status\n      paymentProofStatus\n      paymentProofAttempts\n      paymentProofRejectionReason\n      rejectionReason\n    }\n  }\n"): (typeof documents)["\n  mutation RejectPaymentProof($input: RejectPaymentProofDto!) {\n    rejectPaymentProof(input: $input) {\n      orderId\n      status\n      paymentProofStatus\n      paymentProofAttempts\n      paymentProofRejectionReason\n      rejectionReason\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateAdminOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateAdminOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateAdminOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateAdminOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      userId\n      productId\n      quantity\n      status\n      totalPrice\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation TransitionAdminOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation TransitionAdminOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query AllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query OrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query OrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  query ClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      userId\n      productId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      paymentMethod\n      paymentProofImage\n      paymentProofUploadedAt\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n      paymongoTransactionId\n      paymongoAmount\n      paymongoPaymentMethod\n      paymongoTimestamp\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Login($emailAddress: String!, $password: String!) {\n    login(emailAddress: $emailAddress, password: $password) {\n        message\n    }\n  }\n"): (typeof documents)["\n  mutation Login($emailAddress: String!, $password: String!) {\n    login(emailAddress: $emailAddress, password: $password) {\n        message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation Logout {\n    logout {\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation Logout {\n    logout {\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query readProfile {\n    readProfile {\n      userId\n      fullName\n      emailAddress\n      companyName\n      address\n      phoneNumber\n      role\n    }\n  }\n"): (typeof documents)["\n  query readProfile {\n    readProfile {\n      userId\n      fullName\n      emailAddress\n      companyName\n      address\n      phoneNumber\n      role\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      userId\n      productId\n      quantity\n      unitPrice\n      selectedColor\n      selectedSize\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation AddToCart($input: AddToCartInput!) {\n    addToCart(input: $input) {\n      id\n      userId\n      productId\n      quantity\n      unitPrice\n      selectedColor\n      selectedSize\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      quantity\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateCartItem($input: UpdateCartItemInput!) {\n    updateCartItem(input: $input) {\n      id\n      quantity\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveFromCart($itemId: Int!) {\n    removeFromCart(itemId: $itemId)\n  }\n"): (typeof documents)["\n  mutation RemoveFromCart($itemId: Int!) {\n    removeFromCart(itemId: $itemId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ClearCart {\n    clearCart\n  }\n"): (typeof documents)["\n  mutation ClearCart {\n    clearCart\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveCartItemByProductId($productId: Int!) {\n    removeCartItemByProductId(productId: $productId)\n  }\n"): (typeof documents)["\n  mutation RemoveCartItemByProductId($productId: Int!) {\n    removeCartItemByProductId(productId: $productId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation PlaceOrder($input: PlaceOrderInput!) {\n    placeOrder(input: $input) {\n      success\n      orderNumber\n      message\n      orderId\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  mutation PlaceOrder($input: PlaceOrderInput!) {\n    placeOrder(input: $input) {\n      success\n      orderNumber\n      message\n      orderId\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetCart {\n    getCart {\n      items {\n        id\n        userId\n        productId\n        quantity\n        unitPrice\n        selectedColor\n        selectedSize\n        createdAt\n        updatedAt\n        product {\n          productId\n          productName\n          imageUrl\n          productDescription\n          productPrice\n          category {\n            categoryId\n            categoryName\n          }\n        }\n      }\n      totalItems\n      totalPrice\n    }\n  }\n"): (typeof documents)["\n  query GetCart {\n    getCart {\n      items {\n        id\n        userId\n        productId\n        quantity\n        unitPrice\n        selectedColor\n        selectedSize\n        createdAt\n        updatedAt\n        product {\n          productId\n          productName\n          imageUrl\n          productDescription\n          productPrice\n          category {\n            categoryId\n            categoryName\n          }\n        }\n      }\n      totalItems\n      totalPrice\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation InitiatePaymongoCheckout($orderId: Int!) {\n    initiatePaymongoCheckout(orderId: $orderId) {\n      success\n      paymentIntentId\n      checkoutUrl\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation InitiatePaymongoCheckout($orderId: Int!) {\n    initiatePaymongoCheckout(orderId: $orderId) {\n      success\n      paymentIntentId\n      checkoutUrl\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreateOrder($input: CreateOrderDto!) {\n    createOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdateOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdateOrder($input: UpdateOrderDto!) {\n    updateOrder(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation TransitionOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation TransitionOrderStatus($input: TransitionOrderStatusDto!) {\n    transitionOrderStatus(input: $input) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n"): (typeof documents)["\n  query GetClientOrders {\n    clientOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetOrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n"): (typeof documents)["\n  query GetOrderDetails($orderId: Int!) {\n    orderDetails(orderId: $orderId) {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n"): (typeof documents)["\n  query GetAllOrders {\n    allOrders {\n      orderId\n      orderNumber\n      productId\n      userId\n      orderType\n      quantity\n      unitPrice\n      totalPrice\n      deliveryFee\n      grandTotal\n      status\n      deliveryStatus\n      createdAt\n      updatedAt\n      paymentProofImage\n      paymentProofStatus\n      paymentProofRejectionReason\n      paymentProofAttempts\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetNotificationsByUserId {\n    getNotificationsByUserId {\n      notificationId\n      userId\n      type\n      title\n      message\n      orderId\n      isRead\n      createdAt\n      readAt\n      metadata\n    }\n  }\n"): (typeof documents)["\n  query GetNotificationsByUserId {\n    getNotificationsByUserId {\n      notificationId\n      userId\n      type\n      title\n      message\n      orderId\n      isRead\n      createdAt\n      readAt\n      metadata\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkNotificationAsRead($notificationId: Int!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n"): (typeof documents)["\n  mutation MarkNotificationAsRead($notificationId: Int!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n"): (typeof documents)["\n  mutation MarkAllNotificationsAsRead {\n    markAllNotificationsAsRead {\n      notificationId\n      isRead\n      readAt\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;